corp_print/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('frontend.urls')),
    # path('', include('graphredactor.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('corp_print_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

corp_print_app/urls.py
"""Определяет схемы URL для приложения corp_print_app"""

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy

app_name = 'corp_print_app'

urlpatterns = [
 # Домашняя страница
   #path('login/', views.user_login, name='login'),
   path('login/', auth_views.LoginView.as_view(), name='login'),
   path('logout/', auth_views.LogoutView.as_view(), name='logout'),
   path('', views.index, name='index'),
   path('printed_production/', views.printed_production, name='printed_production'),
   path('password_change/', auth_views.PasswordChangeView.as_view(
      success_url=reverse_lazy('corp_print_app:password_change_done')), name='password_change'),
   path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
   path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
   path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
   path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
   path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
   path('register/', views.register, name='register'),
   path('edit/', views.edit, name='edit'),
   path('edit_template/<int:template_id>/', views.edit_template, name='edit_template'),
]

corp_print_app/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)
    

class PrintTemplate(models.Model):
    name = models.CharField(max_length=100)
    size = models.CharField(max_length=50)
    background_image = models.ImageField(upload_to='corp_print_app/media/')
    logo = models.ImageField(upload_to='corp_print_app/media/', blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    font = models.CharField(max_length=50, blank=True, null=True)
    # Другие поля по вашему усмотрению

    def __str__(self):
        return self.name

corp_print_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, PrintTemplate

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')
        
class PrintTemplateForm(forms.ModelForm):
    class Meta:
        model = PrintTemplate
        fields = ['name', 'size', 'background_image', 'logo', 'text', 'font']

corp_print_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm, PrintTemplateForm
from .models import Profile, PrintTemplate


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponse('Авторизация прошла успешно!')
            else:
                return HttpResponse('Учетная запись деактивирована.')
        else:
            return HttpResponse('Неправильный логин или пароль.')
    else:
        form = LoginForm()
    return render(request, 'corp_print_app/login.html', {'form': form})

@login_required
def printed_production(request):
    return render(request,
                  'corp_print_app/printed_production.html',
                  {'section': 'printed_production'})

def index(request):
    return render(request,
                  'corp_print_app/index.html')

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request,
                          'corp_print_app/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'corp_print_app/register.html',
                  {'user_form': user_form})

@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,
                  'corp_print_app/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})
    

def edit_template(request, template_id):
    # Получаем объект шаблона по его ID
    template = get_object_or_404(PrintTemplate, pk=template_id)

    if request.method == 'POST':
        # Если данные были отправлены методом POST, обрабатываем форму
        form = PrintTemplateForm(request.POST, request.FILES, instance=template)
        if form.is_valid():
            form.save()
            # После успешного сохранения шаблона, перенаправляем пользователя на другую страницу, например на страницу с подробностями о шаблоне
            return redirect('corp_print_app/index.html', template_id=template.id)
    else:
        # Если данные не были отправлены методом POST, создаем форму на основе существующего шаблона
        form = PrintTemplateForm(instance=template)

    return render(request, 'corp_print_app/edit_template.html', {'form': form})

corp_print_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>

<body>
    <div id="header">
        <span class="logo">Corp Print</span>
        {% if request.user.is_authenticated %}
        <ul class="menu">
            <li {% if section == "printed_production" %}class="selected" {% endif %}>
                <a href="{% url "corp_print_app:printed_production" %}">Печатная продукция</a>
            </li>
            <li {% if section == "images" %}class="selected" {% endif %}>
                <a href="#">Images</a>
            </li>
            <li {% if section == "people" %}class="selected" {% endif %}>
                <a href="#">People</a>
            </li>
        </ul>
        {% endif %}

        <span class="user">
            {% if request.user.is_authenticated %}
            Hello {{ request.user.first_name }},
            <form method="post" action="{% url 'corp_print_app:logout' %}">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
            {% else %}
            <a href="{% url "corp_print_app:login" %}">Log-in</a>
            {% endif %}
        </span>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}">
            {{ message|safe }}
            <a href="#" class="close">x</a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

</body>

</html>

corp_print_app/templates/corp_print_app/edit.html
{% extends "base.html" %}

{% block title %}Edit your account{% endblock %}

{% block content %}
  <h1>Edit your account</h1>
  <p>You can edit your account using the following form:</p>
  <form action="." method="post" enctype="multipart/form-data">
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Save changes"></p>
  </form>
{% endblock %}

corp_print_app/templates/corp_print_app/edit_template.html
{% extends "base.html" %}

{% block title %}Edit Print Template{% endblock title %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

{% endblock content %}

corp_print_app/templates/corp_print_app/index.html
{% extends "base.html" %}

{% block title %}Печатная продукция{% endblock %}

{% block content %}
<h1>Печатная продукция!</h1>
<p>Тут будет отображаться печатная продукция.</p>
{% endblock %}

corp_print_app/templates/corp_print_app/login.html
{% extends "corp_print_app/base.html" %}

{% block title %}Log-in{% endblock %}

{% block content %}
<h1>Авторизация</h1>
<p>Используйте форму ниже для авторизации:</p>
<form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Log in"></p>
</form>
<p><a href="{% url "password_reset" %}">Forgotten your  password?</a></p>
{% endblock %}

corp_print_app/templates/corp_print_app/printed_production.html
{% extends "base.html" %}

{% block title %}Печатная продукция{% endblock %}

{% block content %}
<h1>Печатная продукция!</h1>
<p>Welcome to your dashboard. You can <a href="{% url "corp_print_app:edit" %}">edit your profile</a> or <a href="{% url "corp_print_app:password_change" %}">change your password</a>.</p>
{% endblock %}

corp_print_app/templates/corp_print_app/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
<h1>Create an account</h1>
<p>Please, sign up using the following form:</p>
<form action="." method="post">
    {{ user_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Create my account"></p>
</form>
{% endblock %}

corp_print_app/templates/corp_print_app/register_done.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
<h1>Welcome {{ new_user.first_name }}!</h1>
<p>Your account has been successfully created. Now you can <a href="{% url "corp_print_app:login" %}">log in</a>.</p>
{% endblock %}